### ISSUE TITLE
Simplify ElasticSearch mapping of metadata

### ISSUE THREAD

**Issue by solth** [kitodo/kitodo-production#4266]
Currently, process metadata is saved in the following JSON structure in the ElasticSearch index:
<img width="473" alt="Bildschirmfoto 2021-03-12 um 10 49 49" src="https://user-images.githubusercontent.com/19183925/110923108-cf987780-8320-11eb-9373-ad29043ee31c.png">
Since Kitodo.Production internally always uses METS as the container format for metadata, the nodes `mdWrap`, `xmlData` and `kitodo` are not really required and unnecessarily complicate dealing with metadata retrieved from the search index. 

I would therefore propose to remove the nodes mentioned above and directly save all metadata for a given structure element as a JSON array associated directly with the structure elements UUID.

**Comment by matthias-ronge** [comment]
We should think twice about this when redesigning the search engine integration. In any case, the user should be able to search for metadata, also specifically, i.e. that a certain metadata has a certain value. As I would understand, a separate search field would have to be written in the index for each searchable metadata key (except ElasticSearch offers an additional functionality here that I don't know about).

**Comment by solth** [comment]
I am sorry, perhaps there was a misunderstanding. My idea was to remove just the `mdWrap`, `xmlData` and `kitodo` nodes, not the `metadata` node or its content. So all key values pairs concerning metadata entries and groups would be retained.
For example:
```
meta:
    0:
        mdWrap:
            xmlData:
                kitodo:
                    metadata:
        ID:
    1:
        mdWrap:
            xmlData:
                kitodo:
                    metadata:
        ID:
...
```
would become:
```
meta:
    0:
        metadata:
        ID:
    1:
        metadata:
        ID:
...
```
